### ISSUE TITLE
Mapping in collectEntityNamesRecursively:mapping: is sometimes nil

### ISSUE THREAD

**Issue by armandzwan** [lucasmedeirosleite/EasyMapping#159] opened 2017-10-24 09:26 UTC
I updated from 18.1 to the latest version, and now this function is crashing on me because
`EKManagedObjectMapping * mapping = (EKManagedObjectMapping *)[[oneMapping objectClass] objectMapping];`
returns nil.

When I do a `[ManagedObject registerMapping....]` before calling `arrayOfObjectsFromExternalRepresentation`
everything works as expected. But I never had to do a registerMapping before. Something has changed, or am I doing something wrong?

**Comment by armandzwan** [comment] 2017-10-25 07:13
Extra info: It feels unnatural to have to do something like this:
`[LocationWaterwayInstanceZ registerMapping:[self locationWaterwayInstanceMapping]];`
`[mapping hasOne: [LocationWaterwayInstanceZ class] forKeyPath:@"HasPlannedLocationWaterway" forProperty:@"hasLocationWaterwayInstance" withObjectMapping:[self locationWaterwayInstanceMapping]];`

`[self locationWaterwayInstanceMapping]` in withObjectMapping: is not being used in collectEntityNamesRecursively...

**Comment by DenHeadless** [comment] 2017-10-28 08:18
Hey!

`registerMapping` is a method used in our test suite to more conveniently switch between mappings, but you should not need to use this method at all in your own code. Can you post mappings you are using and how you are using them?

**Comment by armandzwan** [comment] 2017-10-30 13:22
I have simplified the mappings to show what I do generally:

```
// general mapping provider
+ (EKManagedObjectMapping *)_objectMapping {
    return [EKManagedObjectMapping mappingForEntityName:NSStringFromClass([ObjectZ class]) withBlock:^(EKManagedObjectMapping *mapping)
            {
                
                mapping.ignoreMissingFields = YES;
                mapping.primaryKey = @"objectId";
                [mapping mapPropertiesFromDictionary:@{@"ObjectID" : @"objectId"}];
                
                // features
                [mapping hasMany:[FeatureZ class] forKeyPath:@"HasFeatures" forProperty:@"hasFeatures" withObjectMapping:[FeatureMappingProvider featureMapping]];
            }];
}

// FeatureMappingProvider
+ (EKManagedObjectMapping *)featureMapping{
    return [EKManagedObjectMapping mappingForEntityName:NSStringFromClass([FeatureZ class]) withBlock:^(EKManagedObjectMapping *mapping)
            {
                mapping.ignoreMissingFields = YES;
                mapping.primaryKey = @"featureId";
                [mapping mapKeyPath:@"ObjectID" toProperty:@"featureId"]; // this is how GapplessBackend tells me
                
                [mapping hasOne:[GISLayerZ class] forKeyPath:@"Object_LayerReference" forProperty:@"inLayer" withObjectMapping:[self layerMapping]];
             }];
}

+ (EKManagedObjectMapping *)layerMapping{
    
    return [EKManagedObjectMapping mappingForEntityName:NSStringFromClass([LayerZ class]) withBlock:^(EKManagedObjectMapping *mapping)
            {
                mapping.ignoreMissingFields = YES;
                mapping.primaryKey = @"layerId";
                
                [mapping mapKeyPath:@"LayerID" toProperty:@"layerId"];
                [mapping mapKeyPath:@"Name" toProperty:@"name"];
            }];
}

**Comment by armandzwan** [comment] 2017-10-30 13:29
So I have a list of Objects in the root, and they have references to Features. These references are very small JSON objects like:
{ "Object_FeatureReference" : 
  {
     "FeatureID" : 10012
  }
}
The features themselves have references to Layers. The Layers are defined within Projects.
This used to work in 0.18.1 but since 0.21.2 not anymore.

**Comment by armandzwan** [comment] 2017-11-23 08:30
Any ideas?

**Comment by armandzwan** [comment] 2020-07-07 14:12
Was trying to upgrade from 0.18 again today. 

With 0.18 I get only one object in Core Data:
![Schermafbeelding 2020-07-07 om 16 04 42](https://user-images.githubusercontent.com/7809728/86794098-64e5bc80-c06c-11ea-8cb3-48852efe66c1.png)  

With the latest version two objects with the same primary key (uuid):  
![Schermafbeelding 2020-07-07 om 16 08 57](https://user-images.githubusercontent.com/7809728/86794234-8fd01080-c06c-11ea-856d-87175f1733fc.png)

So something has changed, or I was doing things wrong already, and now bites me...

**Comment by armandzwan** [comment] 2020-07-08 11:14
It works if I add
```
if (dictionary[mapping.entityName] == nil) {
    dictionary[mapping.entityName] = [[NSMutableSet alloc] init];
}
```
to this piece of code
```
if (value && value != (id)[NSNull null]) {
    [(NSMutableSet *)dictionary[mapping.entityName] addObject:value];
}
```
in `EKCoreDataImporter` like so:
```
if ([rootRepresentation isKindOfClass:[NSArray class]])
    {
        for (NSDictionary * objectInfo in rootRepresentation)
        {
            id value = [self primaryKeyValueFromRepresentation:objectInfo usingMapping:mapping context:context];
            if (value && value != (id)[NSNull null])
            {
                if (dictionary[mapping.entityName] == nil) {
                    dictionary[mapping.entityName] = [[NSMutableSet alloc] init];
                }
                [(NSMutableSet *)dictionary[mapping.entityName] addObject:value];
            }
        }
    }
```
Am I missing something? It seems only to be happening with one type of NSManagedObject.

**Comment by DenTelezhkin** [comment] 2020-07-09 20:41
Sorry, currently don't have time to investigate. If you are able to find issue and contribute a fix or at least a test demonstrating a problem, I will try to help as soon as I find some time.

**Comment by DenTelezhkin** [comment] 2020-08-09 20:28
Please reproduce this problem in example project or unit test, because unfortunately there's not enough information to work on a fix.

Closing this issue for now.

**Closed by DenTelezhkin** 2020-08-09 20:28 UTC
Labels: awaiting feedback, question
